//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace z.ERP.WebServiceTests.erpservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="erpservice.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Do", ReplyAction="http://tempuri.org/IService/DoResponse")]
        z.WebServiceBase.Model.ResponseDTO Do(z.WebServiceBase.Model.RequestDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Do", ReplyAction="http://tempuri.org/IService/DoResponse")]
        System.Threading.Tasks.Task<z.WebServiceBase.Model.ResponseDTO> DoAsync(z.WebServiceBase.Model.RequestDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        z.WebServiceBase.Model.LoginResponseDTO Login(z.WebServiceBase.Model.LoginRequestDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<z.WebServiceBase.Model.LoginResponseDTO> LoginAsync(z.WebServiceBase.Model.LoginRequestDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : z.ERP.WebServiceTests.erpservice.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<z.ERP.WebServiceTests.erpservice.IService>, z.ERP.WebServiceTests.erpservice.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public z.WebServiceBase.Model.ResponseDTO Do(z.WebServiceBase.Model.RequestDTO dto) {
            return base.Channel.Do(dto);
        }
        
        public System.Threading.Tasks.Task<z.WebServiceBase.Model.ResponseDTO> DoAsync(z.WebServiceBase.Model.RequestDTO dto) {
            return base.Channel.DoAsync(dto);
        }
        
        public z.WebServiceBase.Model.LoginResponseDTO Login(z.WebServiceBase.Model.LoginRequestDTO dto) {
            return base.Channel.Login(dto);
        }
        
        public System.Threading.Tasks.Task<z.WebServiceBase.Model.LoginResponseDTO> LoginAsync(z.WebServiceBase.Model.LoginRequestDTO dto) {
            return base.Channel.LoginAsync(dto);
        }
    }
}
